### ISSUE TITLE
Tag 0.28 version?

### ISSUE THREAD

**Issue by olebole** [cds-astro/cds-healpix-java#14]
Hi,

as I am currently upgrading starjava (STIL, STILTS, TOPCAT) in Debian, I found that it contains now [a specific test](https://github.com/Starlink/starjava/blob/bb44e29b82ed79278d9533d45b87fd8de620c463/table/src/testcases/uk/ac/starlink/table/join/CdsHealpixTest.java#L9-L18) for a bug in cds-healpix-java. This bug was actually fixed in 8d607b7f3ad06cd963cc8b3598b865f7de317da9, and the fixed library is [included as a jar in Starjava with version number 0.28](https://github.com/Starlink/starjava/commit/45a868311915c8a4e1ecae044d95ea346865c615).
To keep the version numbers consistent: would it be possible to tag the current master as `v0.28` or `v0.28.1`? I then could update its Debian package as a dependency of Starjava-tables. This is not absolutely required for me, but it would help to keep the versions in sync.

Thanks,

Olebole (Debian maintainer of both cds-healpix-java and starjava-table)

**Comment by fxpineau** [comment]
Done
