### ISSUE TITLE
AssertionError in vertex calculation

### ISSUE THREAD

**Issue by mbtaylor** [cds-astro/cds-healpix-java#16]
The following program throws an AssertionError (if run with `-enableassertions`) in the `vertex` invocation:
```
import cds.healpix.CompassPoint;
import cds.healpix.Healpix;
import cds.healpix.VerticesAndPathComputer;

public class Vert {
    public static void main( String[] args ) {
        int order = 4;
        int hash = 87;
        CompassPoint.Cardinal cardinal = CompassPoint.Cardinal.N;
        VerticesAndPathComputer vc = Healpix.getNestedFast(order);
        double[] lonlat = vc.vertex(hash, cardinal);
        System.out.println(lonlat[0] + ", " + lonlat[1]);
    }
}
```

**Comment by mbtaylor** [comment]
Further: if called with `order = 1`, `hash = 3` and assertions disabled, then `lonlat[0]` is NaN.  Using `getNested` instead of `getNestedFast` seems to be OK.

**Comment by fxpineau** [comment]
Indeed, `HealpixNestedFast.vertex` was bugged. Thank you for the report. 
I have added a test to cross-check `HealpixNested.vertex` with `HealpixNestedFast.vertex`.
