### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by cdeil** [cds-astro/cds-healpix-java#3]
@fxpineau - If I follow the instructions in https://github.com/cds-astro/cds-healpix-java#install I get test errors.

See: https://gist.github.com/cdeil/e563a5e19c7288944e7caa12339e21ed

Wait, what was it? Write once, run somewhere? Or do you see the same?

Actually, I'm not a Java guy and don't really know what's going on.
I see several errors and tracebacks in the JUnit output, but at the very end I see this!?
```
make.test:

BUILD SUCCESSFUL
Total time: 4 minutes 59 seconds
```

**Comment by cdeil** [comment]
This is with `java` and `and` installed via Homebrew on macOS:
```
(gammapy-dev) hfm-1804a:cds-healpix-java deil$ ant -version
Apache Ant(TM) version 1.10.5 compiled on July 10 2018
(gammapy-dev) hfm-1804a:cds-healpix-java deil$ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

**Comment by fxpineau** [comment]
I have now solved all tests errors (at least on my machine).
