### ISSUE TITLE
Problem with the CLI

### ISSUE THREAD

**Issue by mreineck** [cds-astro/cds-healpix-java#4]
I don't manage to get the CLI to work. Whichever action I specify, I get an "unknown action" error.

I think this can be fixed by replacing all "==" operators between strings in `HealpixCLI.java` by `.equals()`. However I'm sure I'm not the first one to notice this ... so am I missing something obvious?

**Comment by fxpineau** [comment]
I confirm.
I think I originally used a switch/case on strings and replaced the switch too quickly by if/else to be compatible with Java 6.
The problem will be solve in the next commit.
