### ISSUE TITLE
Tag a version?

### ISSUE THREAD

**Issue by olebole** [cds-astro/cds-healpix-java#6]
Hi,

cds-healpix-java is a new dependency of the upcoming Aladin version, and I would like to [package it for Debian as a separate package](https://bugs.debian.org/943942). Maintenance for me would be easier when you could provide (tag) versions that are supposed to use.

Could I ask you to tag a version of the package?

Best regards

Ole

**Comment by fxpineau** [comment]
Done

**Comment by olebole** [comment]
Thank you!

**Comment by olebole** [comment]
FYI, our development repository is https://salsa.debian.org/debian-astro-team/cds-healpix-java 
This is identical to the released version, all changes we do are in the [`debian/` subdirectory](https://salsa.debian.org/debian-astro-team/cds-healpix-java/tree/master/debian).
